name: líng
favicon: null
layout_spectrum: 0.943707
typography_spectrum: 0.7571669
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: líng - the chinese pinyin for 'spirit'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F6EEEC'
    - '#44462F'
    - '#656241'
    - '#AA8C56'
    - '#C4AE99'
  brandStrength: 0.2668085
  lightness: 0.8752108
  saturation: 0.8145025
  rhythmicContrast: 0.4418212
purpose: []
