layout_spectrum: 0.943707
typography_spectrum: 0.05059022
color:
  saturation: 0.8145025
  brandStrength: 0.2668085
  lightness: 0.8752108
  rhythmicContrast: 0.4418212
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
name: líng
