layout_spectrum: 0.943707
typography_spectrum: 0.6450253
color:
  saturation: 0.8145025
  brandStrength: 0.2668085
  lightness: 0.8752108
  brandColors:
    - '#F6EEEC'
    - '#44462F'
    - '#656241'
    - '#AA8C56'
    - '#C4AE99'
  rhythmicContrast: 0.4418212
name: líng
